---
- name: Converge
  hosts: molecule
  gather_facts: true
  environment:
    ANSIBLE_COLLECTIONS_PATH: "/runner/requirements_collections"
  tasks:
    - name: Error out if registry username is not set
      ansible.builtin.fail:
        msg: "Username for registry.redhat.io is not set, please provide it via TAS_SINGLE_NODE_REGISTRY_USERNAME env variable"
      when: tas_single_node_registry_username == ""

    - name: Error out if registry password is not set
      ansible.builtin.fail:
        msg: "Password for registry.redhat.io is not set, please provide it via TAS_SINGLE_NODE_REGISTRY_PASSWORD env variable"
      when: tas_single_node_registry_password == ""

    - name: Install redhat.artifact_signer collection from the private AAP
      delegate_to: localhost
      ansible.builtin.shell:
        cmd: |
          ansible-galaxy collection install redhat.artifact_signer -s https://{{ aap_instance_ip }}/pulp_ansible/galaxy/staging/api/ \
          --ignore-certs --token {{ token }} --force -p /runner/requirements_collections
      changed_when: false

    - name: Verify redhat.artifact_signer collection is installed
      delegate_to: localhost
      ansible.builtin.shell:
        cmd: ls /runner/requirements_collections/ansible_collections/redhat/ | grep artifact_signer
      register: collection_check
      failed_when: collection_check.rc != 0

    - name: Apply redhat.artifact_signer.tas_single_node role from the private AAP
      ansible.builtin.include_role:
        name: redhat.artifact_signer.tas_single_node
      collections:
        - redhat.artifact_signer
