---
- name: Converge
  hosts: molecule
  gather_facts: true
  tasks:
    - name: Error out if registry username is not set
      ansible.builtin.fail:
        msg: "Username for registry.redhat.io is not set, please provide it via TAS_SINGLE_NODE_REGISTRY_USERNAME env variable"
      when: tas_single_node_registry_username == ""

    - name: Error out if registry password is not set
      ansible.builtin.fail:
        msg: "Password for registry.redhat.io is not set, please provide it via TAS_SINGLE_NODE_REGISTRY_PASSWORD env variable"
      when: tas_single_node_registry_password == ""

    - name: List roles in the redhat.artifact_signer collection
      delegate_to: localhost
      ansible.builtin.shell:
        cmd: ansible-config dump | grep COLLECTIONS
      register: roles_list
      changed_when: false

    - name: Display roles in the redhat.artifact_signer collection
      ansible.builtin.debug:
        msg: "{{ roles_list.stdout_lines }}"

    - name: List all collections in defined paths
      delegate_to: localhost
      ansible.builtin.shell:
        cmd: ls -R {{ item }}
      with_items:
        - /runner/requirements_collections
        - /home/runner/.ansible/collections
        - /usr/share/ansible/collections
      register: collections_list
      ignore_errors: true
      changed_when: false

    - name: Display collections found in each path
      ansible.builtin.debug:
        msg: |
          Path: {{ item.item }}
          Output:
          {{ item.stdout_lines | default(['No collections found in this path.']) }}
      with_items: "{{ collections_list.results }}"

    # - name: Install redhat.artifact_signer collection from the private AAP
    #   delegate_to: localhost
    #   ansible.builtin.shell:
    #     cmd: |
    #       ansible-galaxy collection install redhat.artifact_signer -s https://{{ aap_instance_ip }}/pulp_ansible/galaxy/staging/api/ \
    #       --ignore-certs --token {{ token }} --force
    #   changed_when: false

    # - name: Verify redhat.artifact_signer collection is installed
    #   delegate_to: localhost
    #   ansible.builtin.shell:
    #     cmd: |
    #       bash -c 'set -o pipefail && ansible-galaxy collection list | grep redhat.artifact_signer'
    #   register: collection_check
    #   changed_when: false
    #   failed_when: collection_check.rc != 0

    - name: Apply redhat.artifact_signer.tas_single_node role from the private AAP
      ansible.builtin.include_role:
        name: redhat.artifact_signer.tas_single_node
      collections:
        - redhat.artifact_signer
